version: '3'
services:
  auth-service:
    image: yurademenev/hse_auth-service
    ports:
      - "8000:8000"
    restart: always

  task-service:
    image: yurademenev/hse_task-service
    ports:
      - "8001:8001"
    restart: always

#hostname -I
